name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: pipx install uv

    - name: Install just
      uses: extractions/setup-just@v2

    - name: Run just setup
      run: just setup

    - name: Run e2e tests
      run: just e2e-test